name: easy-exam

services:
  easy-exam:
    image: ailm32442/easy-exam:latest
    build: .
    container_name: easy-exam
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - LLM_BASE_URL=http://host.docker.internal:11434/v1
      - EASYEXAM_SECRET_KEY=${EASYEXAM_SECRET_KEY}
