#!/usr/bin/env python3
"""Cross-platform installer for Git pre-commit hook.

Hardened against:
1. Windows CRLF line-ending corruption (enforces pure LF \\n for POSIX sh)
2. Git worktree and submodule paths (uses `git rev-parse --git-path hooks`)
3. Multi-language collision (Node.js, Python, Go, Rust proper detection)
4. Python virtual environment isolation (.venv / venv / env)
"""
import os
import shutil
import subprocess
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# NOTE: Must strictly use \\n (LF) to avoid '/bin/sh^M: bad interpreter' on Linux/macOS/Git Bash.
HOOK_SHELL_SCRIPT = """#!/bin/sh
# Git pre-commit hook: Auto-runs test suite & security checks before any commit.
# Generated by Vibe Coding Starter

echo "============================================================"
echo " [Git Pre-Commit Gate] Running security checks & test suite..."
echo "============================================================"

# Python interpreter probe
PYTHON_EXEC=""
if [ -f ".venv/bin/python" ]; then
    PYTHON_EXEC=".venv/bin/python"
elif [ -f ".venv/Scripts/python.exe" ]; then
    PYTHON_EXEC=".venv/Scripts/python.exe"
elif [ -f "venv/bin/python" ]; then
    PYTHON_EXEC="venv/bin/python"
elif [ -f "venv/Scripts/python.exe" ]; then
    PYTHON_EXEC="venv/Scripts/python.exe"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON_EXEC="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON_EXEC="python"
fi

if [ -z "$PYTHON_EXEC" ]; then
    echo "❌ [BLOCKED] No Python interpreter found (.venv, python3, python)!"
    exit 1
fi

# 1. Run physical guard checks
for check in guard_test_tampering scan_hardcoded_paths; do
    if [ -f "scripts/$check.py" ]; then
        echo "Running guard: scripts/$check.py..."
        $PYTHON_EXEC "scripts/$check.py" || exit 1
    fi
done

# 2. Check custom test command override
if [ -n "$VIBE_TEST_CMD" ]; then
    echo "Running custom VIBE_TEST_CMD: $VIBE_TEST_CMD"
    eval "$VIBE_TEST_CMD"
    RESULT=$?
else
    RESULT=0
    # Run Frontend tests if present
    if [ -f "frontend/package.json" ]; then
        echo "Running frontend unit tests..."
        npm --prefix frontend run test:unit || RESULT=1
    fi

    # Run Python backend tests
    if [ -d "tests" ]; then
        echo "Running backend tests via $PYTHON_EXEC..."
        $PYTHON_EXEC -m unittest discover -s tests -p "test_*.py" || RESULT=1
    fi
fi

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "❌ [BLOCKED] Commit rejected! Test suite did not pass 100% green."
    echo "💡 Fix failures or ensure tests pass before committing."
    echo "💡 To view requirements, check SPEC.md. To inspect rules, check AGENTS.md."
    echo "============================================================"
    exit 1
fi

echo ""
echo "✅ [PASSED] All tests green! Proceeding with commit."
echo "============================================================"
exit 0
"""


def resolve_git_hooks_dir(repo_root: Path) -> Path:
    """Resolve the real hooks directory using git rev-parse (supports worktrees & submodules)."""
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=True
        )
        hooks_rel = proc.stdout.strip()
        if hooks_rel:
            resolved = Path(hooks_rel)
            if not resolved.is_absolute():
                resolved = repo_root / resolved
            return resolved
    except Exception:
        pass
    return repo_root / ".git" / "hooks"


def activate_ci_if_requested(repo_root: Path):
    """Optionally activate GitHub Actions CI from templates/ci.yml."""
    src_ci = repo_root / "templates" / "ci.yml"
    dest_dir = repo_root / ".github" / "workflows"
    dest_ci = dest_dir / "ci.yml"

    if src_ci.exists() and not dest_ci.exists():
        dest_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_ci, dest_ci)
        print("[INFO] Activated GitHub Actions workflow at .github/workflows/ci.yml")


def main():
    repo_root = Path(__file__).resolve().parent.parent
    hooks_dir = resolve_git_hooks_dir(repo_root)

    if not hooks_dir.parent.exists():
        print(f"[ERROR] Git directory not found at {hooks_dir.parent}. Is this a git repository?")
        sys.exit(1)

    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-commit"

    # Enforce pure LF (\\n) line endings across all operating systems
    content = HOOK_SHELL_SCRIPT.replace("\r\n", "\n").encode("utf-8")
    target.write_bytes(content)

    # Set executable flag on POSIX systems
    if os.name != "nt":
        target.chmod(0o755)

    print(f"[SUCCESS] Installed pre-commit hook into {target}")
    print("[INFO] Line endings: Pure Unix LF (POSIX compatible)")
    print("[INFO] Every git commit will now run your tests automatically.")

    # Check for --enable-ci flag
    if "--enable-ci" in sys.argv:
        activate_ci_if_requested(repo_root)


if __name__ == "__main__":
    main()
